# Generated by Django 5.0.7 on 2024-10-24 17:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Admin')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_code', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=250, unique=True)),
                ('department_logo', models.ImageField(blank=True, null=True, upload_to='department_logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_exam_code', models.CharField(max_length=10, null=True, unique=True)),
                ('feedback_exam_name', models.CharField(max_length=50, null=True)),
                ('max_options_per_question', models.PositiveIntegerField(default=2, help_text='Maximum number of options allowed per question in this exam.')),
                ('options_limit_status', models.CharField(default='Not Changed', editable=False, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FailedLoginAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('attempts', models.PositiveBigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudyingYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studying_year', models.PositiveIntegerField(default=1, unique=True)),
                ('studying_year_name', models.CharField(max_length=40)),
                ('academic_year', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('faculty_id', models.CharField(max_length=20, unique=True)),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_image', models.ImageField(blank=True, null=True, upload_to='faculty_images/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.departments')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('feedbackapp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=10)),
                ('branch_name', models.CharField(max_length=250)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.departments')),
                ('studying_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.studyingyear')),
            ],
            options={
                'unique_together': {('branch_code', 'studying_year')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(null=True)),
                ('question_text', models.TextField(null=True)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.exam')),
            ],
            options={
                'unique_together': {('exam', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(default=1, max_length=20)),
                ('section_name', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.branches')),
                ('selected_exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.exam')),
                ('studying_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.studyingyear')),
            ],
            options={
                'unique_together': {('section_number', 'studying_year', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('midterm1_active', models.BooleanField(default=False)),
                ('midterm2_active', models.BooleanField(default=False)),
                ('midterm1_activated_at', models.DateTimeField(blank=True, null=True)),
                ('midterm2_activated_at', models.DateTimeField(blank=True, null=True)),
                ('midterm1_deactivate', models.DateTimeField(blank=True, null=True)),
                ('midterm2_deactivate', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.branches')),
                ('faculty', models.ForeignKey(limit_choices_to={'role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.section')),
                ('studying_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.studyingyear')),
            ],
            options={
                'unique_together': {('section', 'studying_year', 'branch', 'subject_code')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.branches')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.departments')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.section')),
                ('studying_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.studyingyear')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('feedbackapp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_number', models.PositiveIntegerField(null=True)),
                ('option_text', models.CharField(max_length=255)),
                ('option_score', models.PositiveIntegerField(null=True)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.exam')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='feedbackapp.question')),
            ],
            options={
                'unique_together': {('exam', 'question', 'option_number')},
            },
        ),
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.departments')),
                ('faculty_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.faculty')),
            ],
            options={
                'unique_together': {('department', 'faculty_name')},
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options_mid_term_1', models.CharField(max_length=1000, null=True)),
                ('options_mid_term_2', models.CharField(max_length=1000, null=True)),
                ('comments_mid_term_1', models.JSONField(blank=True, null=True)),
                ('comments_mid_term_2', models.JSONField(blank=True, null=True)),
                ('mid_term', models.PositiveIntegerField(blank=True, null=True)),
                ('mid_term_1_rating', models.FloatField(null=True)),
                ('mid_term_2_rating', models.FloatField(null=True)),
                ('over_all_ratings', models.FloatField(null=True)),
                ('created_at_mid_term_1', models.DateTimeField(null=True)),
                ('updated_at_mid_term_1', models.DateTimeField(null=True)),
                ('created_at_mid_term_2', models.DateTimeField(null=True)),
                ('updated_at_mid_term_2', models.DateTimeField(null=True)),
                ('is_submitted_mid_term_1', models.BooleanField(default=False)),
                ('is_submitted_mid_term_2', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.subject')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_feedbacks', to='feedbackapp.faculty')),
            ],
            options={
                'unique_together': {('student', 'faculty', 'subject', 'section')},
            },
        ),
    ]
