# Generated by Django 5.0.7 on 2024-07-23 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_exam_code', models.CharField(max_length=10, null=True, unique=True)),
                ('feedback_exam_name', models.CharField(max_length=50, null=True)),
                ('max_options_per_question', models.PositiveIntegerField(default=2, help_text='Maximum number of options allowed per question in this exam.')),
                ('options_limit_status', models.CharField(default='Not Changed', editable=False, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudyingYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studying_year', models.PositiveIntegerField(default=1, unique=True)),
                ('studying_year_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('student', 'faculty', 'subject', 'section')},
        ),
        migrations.AddField(
            model_name='feedback',
            name='comments_mid_term_1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comments_mid_term_2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at_mid_term_1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at_mid_term_2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_submitted_mid_term_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_submitted_mid_term_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='mid_term_1_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='mid_term_2_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='options_mid_term_1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='options_mid_term_2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='over_all_ratings',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at_mid_term_1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at_mid_term_2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='section_number',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.branches'),
        ),
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.branches'),
        ),
        migrations.AddField(
            model_name='subject',
            name='midterm1_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='midterm1_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='midterm1_deactivate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='midterm2_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='midterm2_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='midterm2_deactivate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.section'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='branch_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='branches',
            name='branch_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_feedbacks', to='feedbackapp.faculty'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.branches'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.exam'),
        ),
        migrations.AddField(
            model_name='section',
            name='selected_exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.exam'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('exam', 'question_number')},
        ),
        migrations.AddField(
            model_name='branches',
            name='studying_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.studyingyear'),
        ),
        migrations.AddField(
            model_name='section',
            name='studying_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.studyingyear'),
        ),
        migrations.AddField(
            model_name='subject',
            name='studying_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.studyingyear'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studying_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.studyingyear'),
        ),
        migrations.AlterUniqueTogether(
            name='branches',
            unique_together={('branch_code', 'studying_year')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('section_number', 'studying_year', 'branch')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('section', 'studying_year', 'branch', 'subject_code')},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='mid_term',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_number', models.PositiveIntegerField(null=True)),
                ('option_text', models.CharField(max_length=255)),
                ('option_score', models.PositiveIntegerField(null=True)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.exam')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='feedbackapp.question')),
            ],
            options={
                'unique_together': {('exam', 'question', 'option_number')},
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sections',
        ),
    ]
