# Generated by Django 5.0.7 on 2024-07-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0002_exam_studyingyear_alter_feedback_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='mid_term',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
