# Generated by Django 5.0.7 on 2024-07-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0003_feedback_mid_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyingyear',
            name='academic_year',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
